name: Feature Request
description: Suggest a new feature or enhancement for Treasury Command Center
title: "[FEATURE]: "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand and evaluate your proposal.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see added.
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: What alternatives have you considered?

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Frontend/Dashboard
        - Backend/API
        - Database
        - Blockchain Integration
        - Authentication
        - Multi-chain Portfolio
        - Stablecoin Management
        - AI Agents
        - Analytics
        - Documentation
        - DevOps/Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve user experience
        - High - Important for core functionality
        - Critical - Blocking adoption or major use case
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple change or addition
        - Medium - Moderate development effort
        - High - Significant development effort
        - Unknown - Need technical analysis

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be valuable.
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. When [scenario], this feature would help by [outcome]

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would constitute a successful implementation of this feature?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or considerations for this feature?
      placeholder: Technical requirements, API changes, database schema changes, etc.

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples to illustrate the feature.
      placeholder: Attach images or describe the UI/UX...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to implementing this feature?
      options:
        - label: I'd like to work on implementing this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature
        - label: I can provide feedback during development

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, research, or resources related to this feature request.
      placeholder: Links to relevant documentation, similar features in other tools, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true