# Polka-Trinity Ultimate AI Trinity - AlertManager Configuration
# Enterprise alerting for trillion-parameter governance intelligence
#
# Alerting Strategy:
# - Immediate notification for Ultimate AI Trinity issues
# - Multi-channel alerting for infrastructure sovereignty
# - Escalation paths for enterprise SLA compliance
# - Cost efficiency violation alerts

global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@nuru.network'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# Enterprise notification templates
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Alert routing configuration
route:
  group_by: ['alertname', 'service', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'enterprise-default'
  
  routes:
    # Critical Ultimate AI Trinity alerts
    - match:
        severity: critical
        service: ultimate-ai-trinity
      receiver: 'trinity-critical'
      group_wait: 10s
      repeat_interval: 1h
    
    # Multi-Xnode infrastructure alerts
    - match:
        infrastructure: multi-xnode
      receiver: 'infrastructure-team'
      group_wait: 30s
      repeat_interval: 2h
    
    # Cost efficiency violations (immediate escalation)
    - match:
        service: cost-monitoring
      receiver: 'executive-escalation'
      group_wait: 0s
      repeat_interval: 15m
    
    # Enterprise SLA compliance
    - match:
        service: sla-monitoring
      receiver: 'enterprise-sla-team'
      group_wait: 1m
      repeat_interval: 30m
    
    # Security and compliance alerts
    - match:
        service: security
      receiver: 'security-team'
      group_wait: 1m
      repeat_interval: 1h

# Receiver configurations
receivers:
  # Default enterprise notifications
  - name: 'enterprise-default'
    email_configs:
      - to: 'devops@nuru.network'
        subject: '[Polka-Trinity] {{ .GroupLabels.alertname }} - {{ .GroupLabels.severity }}'
        body: |
          🚨 Polka-Trinity Ultimate AI Trinity Alert
          
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .GroupLabels.severity }}
          Service: {{ .GroupLabels.service }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          Action: {{ .Annotations.action }}
          {{ end }}
          
          Infrastructure: Multi-Xnode Sovereign Architecture
          AI Models: DeepSeek-R1:671b + Llama4:maverick + Qwen3:235b
          Cost Advantage: $3.6M-6M annual savings maintained
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#polka-trinity-alerts'
        title: '🚨 Polka-Trinity Alert: {{ .GroupLabels.alertname }}'
        text: |
          *Severity:* {{ .GroupLabels.severity }}
          *Service:* {{ .GroupLabels.service }}
          
          {{ range .Alerts }}
          *Description:* {{ .Annotations.description }}
          *Action Required:* {{ .Annotations.action }}
          {{ end }}
          
          🧠 *Ultimate AI Trinity Status:* Monitoring
          💰 *Cost Efficiency:* $0 operational costs maintained

  # Critical Ultimate AI Trinity alerts
  - name: 'trinity-critical'
    email_configs:
      - to: 'trinity-team@nuru.network, cto@nuru.network'
        subject: '🚨 CRITICAL: Ultimate AI Trinity Issue - {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT: Ultimate AI Trinity
          
          This is a critical alert affecting our trillion-parameter governance intelligence platform.
          
          Alert: {{ .GroupLabels.alertname }}
          Impact: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          
          🧠 Models Affected:
          - DeepSeek-R1 (671B parameters) - Mathematical reasoning
          - Llama4:maverick (400B parameters) - Strategic intelligence  
          - Qwen3 (235B MoE parameters) - Global perspective
          
          💰 Business Impact:
          {{ range .Alerts }}
          {{ if .Annotations.cost_impact }}{{ .Annotations.cost_impact }}{{ end }}
          {{ if .Annotations.business_impact }}{{ .Annotations.business_impact }}{{ end }}
          {{ end }}
          
          🏗️ Infrastructure: Multi-Xnode Sovereign (Privacy: 23.92.65.57, Performance: 23.92.65.18)
          
          IMMEDIATE ACTION REQUIRED:
          {{ range .Alerts }}{{ .Annotations.action }}{{ end }}
    
    slack_configs:
      - api_url: '${SLACK_CRITICAL_WEBHOOK_URL}'
        channel: '#trinity-critical'
        title: '🚨 CRITICAL: Ultimate AI Trinity - {{ .GroupLabels.alertname }}'
        color: 'danger'
        text: |
          <!channel> **CRITICAL ALERT**
          
          🧠 **Ultimate AI Trinity Issue Detected**
          
          {{ range .Alerts }}
          **Impact:** {{ .Annotations.description }}
          **Action:** {{ .Annotations.action }}
          {{ if .Annotations.cost_impact }}**Cost Impact:** {{ .Annotations.cost_impact }}{{ end }}
          {{ end }}
          
          📊 **Models:** 1.3+ trillion parameters
          🏗️ **Infrastructure:** Multi-Xnode Sovereign
          💰 **Advantage:** $3.6M-6M annual savings

  # Infrastructure team notifications
  - name: 'infrastructure-team'
    email_configs:
      - to: 'infrastructure@nuru.network'
        subject: '[Infrastructure] {{ .GroupLabels.alertname }} - Multi-Xnode Alert'
        body: |
          🏗️ Multi-Xnode Infrastructure Alert
          
          Alert: {{ .GroupLabels.alertname }}
          Infrastructure: {{ .GroupLabels.infrastructure }}
          
          {{ range .Alerts }}
          Issue: {{ .Annotations.description }}
          Action: {{ .Annotations.action }}
          {{ if .Annotations.sovereignty_risk }}Sovereignty Risk: {{ .Annotations.sovereignty_risk }}{{ end }}
          {{ if .Annotations.performance_impact }}Performance Impact: {{ .Annotations.performance_impact }}{{ end }}
          {{ end }}
          
          🔗 Xnode Status:
          - Privacy Xnode: 23.92.65.57 (Data sovereignty)
          - Performance Xnode: 23.92.65.18 (Ultimate AI Trinity)
    
    discord_configs:
      - webhook_url: '${DISCORD_INFRASTRUCTURE_WEBHOOK}'
        title: '🏗️ Multi-Xnode Infrastructure Alert'
        description: |
          **Alert:** {{ .GroupLabels.alertname }}
          
          {{ range .Alerts }}
          **Issue:** {{ .Annotations.description }}
          **Action:** {{ .Annotations.action }}
          {{ end }}

  # Executive escalation for cost violations
  - name: 'executive-escalation'
    email_configs:
      - to: 'ceo@nuru.network, cfo@nuru.network, cto@nuru.network'
        subject: '🚨 EXECUTIVE ALERT: Cost Efficiency Violation - Polka-Trinity'
        body: |
          🚨 EXECUTIVE ESCALATION REQUIRED
          
          CRITICAL: Cost efficiency violation detected in Polka-Trinity Ultimate AI Trinity platform.
          
          {{ range .Alerts }}
          Violation: {{ .Annotations.description }}
          Competitive Impact: {{ .Annotations.competitive_impact }}
          Required Action: {{ .Annotations.action }}
          {{ end }}
          
          💰 Our Competitive Advantage at Risk:
          - Target: $0 AI operational costs
          - Annual Savings: $3.6M-6M vs cloud AI
          - Infrastructure Sovereignty: 100% customer ownership
          
          This violation requires immediate executive attention to preserve our market-leading cost structure.
    
    slack_configs:
      - api_url: '${SLACK_EXECUTIVE_WEBHOOK_URL}'
        channel: '#executive-alerts'
        title: '🚨 EXECUTIVE: Cost Efficiency Violation'
        color: 'danger'
        text: |
          <!here> **EXECUTIVE ESCALATION**
          
          💰 **Cost efficiency violation detected**
          
          {{ range .Alerts }}
          **Issue:** {{ .Annotations.description }}
          **Impact:** {{ .Annotations.competitive_impact }}
          {{ end }}
          
          **Our $3.6M-6M competitive advantage is at risk**

  # Enterprise SLA team
  - name: 'enterprise-sla-team'
    email_configs:
      - to: 'sla-team@nuru.network, enterprise-support@nuru.network'
        subject: '[SLA] {{ .GroupLabels.alertname }} - Enterprise Compliance Alert'
        body: |
          📊 Enterprise SLA Compliance Alert
          
          Alert: {{ .GroupLabels.alertname }}
          
          {{ range .Alerts }}
          SLA Impact: {{ .Annotations.description }}
          Required Action: {{ .Annotations.action }}
          {{ if .Annotations.sla_impact }}Contract Impact: {{ .Annotations.sla_impact }}{{ end }}
          {{ end }}
          
          🎯 Enterprise SLA Targets:
          - Uptime: 99.9% availability
          - Response Time: <5s for Ultimate AI Trinity
          - Error Rate: <1% for governance analysis

  # Security team notifications
  - name: 'security-team'
    email_configs:
      - to: 'security@nuru.network'
        subject: '[Security] {{ .GroupLabels.alertname }} - Polka-Trinity Security Alert'
        body: |
          🔒 Polka-Trinity Security Alert
          
          Alert: {{ .GroupLabels.alertname }}
          
          {{ range .Alerts }}
          Security Issue: {{ .Annotations.description }}
          Action Required: {{ .Annotations.action }}
          {{ if .Annotations.compliance_note }}Compliance: {{ .Annotations.compliance_note }}{{ end }}
          {{ end }}
          
          🛡️ Security Framework: SOC 2 Type II + ISO 27001
          🏗️ Infrastructure: Multi-Xnode Sovereign Architecture

# Inhibition rules to prevent alert spam
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
  
  - source_match:
      alertname: 'UltimateAITrinityModelUnavailable'
    target_match:
      alertname: 'TrinityResponseTimeHigh'
    equal: ['service']