# Polka-Trinity Ultimate AI Trinity - Enterprise Alert Rules
# Strategic monitoring for trillion-parameter governance intelligence
#
# Alert Categories:
# - Ultimate AI Trinity model availability and performance
# - Multi-Xnode infrastructure health and connectivity
# - Enterprise SLA compliance and cost efficiency validation
# - Security and operational excellence monitoring

groups:
  # Ultimate AI Trinity Model Health
  - name: ultimate_ai_trinity_health
    rules:
      - alert: UltimateAITrinityModelUnavailable
        expr: up{job="ultimate-ai-trinity"} == 0
        for: 2m
        labels:
          severity: critical
          service: ultimate-ai-trinity
          infrastructure: multi-xnode
        annotations:
          summary: "Ultimate AI Trinity model unavailable"
          description: "One or more flagship models (DeepSeek-R1:671b, Llama4:maverick, Qwen3:235b) are unavailable for {{ $value }} minutes. This impacts trillion-parameter governance analysis."
          action: "Verify Multi-Xnode connectivity and model health"
          cost_impact: "$0 operational costs maintained (competitive advantage preserved)"

      - alert: TrinityResponseTimeHigh
        expr: histogram_quantile(0.95, rate(trinity_request_duration_seconds_bucket[5m])) > 5
        for: 3m
        labels:
          severity: warning
          service: ultimate-ai-trinity
        annotations:
          summary: "Ultimate AI Trinity response time degraded"
          description: "95th percentile response time is {{ $value }}s (target: <5s)"
          action: "Check Multi-Xnode performance and model coordination"

      - alert: TrinityParameterEfficiencyDegraded
        expr: trinity_parameters_utilized / trinity_parameters_total < 0.8
        for: 5m
        labels:
          severity: warning
          service: ultimate-ai-trinity
        annotations:
          summary: "Ultimate AI Trinity parameter efficiency below target"
          description: "Only {{ $value | humanizePercentage }} of 1.3+ trillion parameters being effectively utilized"
          action: "Optimize model coordination and request distribution"

  # Multi-Xnode Infrastructure Health
  - name: multi_xnode_infrastructure
    rules:
      - alert: PrivacyXnodeUnreachable
        expr: up{instance="23.92.65.57:9100"} == 0
        for: 2m
        labels:
          severity: critical
          service: privacy-xnode
          infrastructure: multi-xnode
        annotations:
          summary: "Privacy Xnode (23.92.65.57) unreachable"
          description: "Privacy Xnode connectivity lost - impacts data sovereignty"
          action: "Verify Xnode infrastructure and network connectivity"
          sovereignty_risk: "High - customer data sovereignty may be compromised"

      - alert: PerformanceXnodeUnreachable
        expr: up{instance="23.92.65.18:9100"} == 0
        for: 2m
        labels:
          severity: critical
          service: performance-xnode
          infrastructure: multi-xnode
        annotations:
          summary: "Performance Xnode (23.92.65.18) unreachable"
          description: "Performance Xnode connectivity lost - impacts Ultimate AI Trinity"
          action: "Verify Xnode infrastructure and Ollama service status"
          performance_impact: "High - trillion-parameter analysis unavailable"

      - alert: XnodeLatencyHigh
        expr: xnode_response_time_seconds > 0.2
        for: 3m
        labels:
          severity: warning
          service: multi-xnode
        annotations:
          summary: "Multi-Xnode latency elevated"
          description: "Xnode response time {{ $value }}s exceeds 200ms target"
          action: "Check network connectivity and Xnode performance"

  # Enterprise API Performance
  - name: polka_trinity_api_health
    rules:
      - alert: PolkaTrinityAPIDown
        expr: up{job="polka-trinity-api"} == 0
        for: 1m
        labels:
          severity: critical
          service: polka-trinity-api
        annotations:
          summary: "Polka-Trinity API service down"
          description: "Enhanced Event API (port 8099) is unavailable"
          action: "Restart API service and verify container health"
          business_impact: "High - enterprise customers cannot access governance analysis"

      - alert: PolkaTrinityHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="polka-trinity-api"}[5m])) > 3
        for: 5m
        labels:
          severity: warning
          service: polka-trinity-api
        annotations:
          summary: "Polka-Trinity API high latency"
          description: "95th percentile API response time is {{ $value }}s"
          action: "Check system resources and Ultimate AI Trinity coordination"

      - alert: PolkaTrinityErrorRateHigh
        expr: rate(http_requests_total{job="polka-trinity-api",status=~"5.."}[5m]) / rate(http_requests_total{job="polka-trinity-api"}[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
          service: polka-trinity-api
        annotations:
          summary: "Polka-Trinity API error rate elevated"
          description: "Error rate is {{ $value | humanizePercentage }} (target: <5%)"
          action: "Check application logs and Ultimate AI Trinity status"

  # Database and Infrastructure
  - name: database_infrastructure
    rules:
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 2m
        labels:
          severity: critical
          service: postgresql
        annotations:
          summary: "PostgreSQL database unavailable"
          description: "Polka-Trinity database is down"
          action: "Restart PostgreSQL service and check data integrity"

      - alert: PostgreSQLConnectionsHigh
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL connection utilization high"
          description: "Database connections at {{ $value | humanizePercentage }} of maximum"
          action: "Monitor connection pooling and application queries"

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis memory utilization high"
          description: "Redis memory usage at {{ $value | humanizePercentage }}"
          action: "Review cache policies and consider memory optimization"

  # Enterprise Security and Compliance
  - name: security_compliance
    rules:
      - alert: UnauthorizedAccessAttempt
        expr: increase(http_requests_total{status="401"}[5m]) > 10
        for: 1m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Multiple unauthorized access attempts detected"
          description: "{{ $value }} failed authentication attempts in 5 minutes"
          action: "Review security logs and consider IP blocking"
          compliance_note: "SOC 2 / ISO 27001 security monitoring active"

      - alert: CertificateExpiringSoon
        expr: (ssl_certificate_expiry_seconds - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
          service: security
        annotations:
          summary: "SSL certificate expiring soon"
          description: "Certificate expires in {{ $value }} days"
          action: "Renew SSL certificate for enterprise.polka-trinity.nuru.network"

  # Cost Efficiency and Competitive Advantage
  - name: cost_efficiency_monitoring
    rules:
      - alert: CostEfficiencyValidation
        expr: ai_operational_costs_usd > 0
        for: 1m
        labels:
          severity: critical
          service: cost-monitoring
        annotations:
          summary: "CRITICAL: AI operational costs detected"
          description: "Operational costs of ${{ $value }} detected - violates $0 cost advantage"
          action: "Immediately verify Multi-Xnode architecture integrity"
          competitive_impact: "SEVERE - $3.6M-6M annual savings advantage compromised"

      - alert: InfrastructureSovereigntyRisk
        expr: external_ai_api_calls_total > 0
        for: 1m
        labels:
          severity: warning
          service: sovereignty-monitoring
        annotations:
          summary: "Infrastructure sovereignty risk detected"
          description: "{{ $value }} external AI API calls detected"
          action: "Verify all AI processing occurs on customer-owned Xnodes"
          sovereignty_note: "100% customer ownership must be maintained"

  # Enterprise SLA Monitoring
  - name: enterprise_sla_compliance
    rules:
      - alert: UptimeSLABreach
        expr: (time() - process_start_time_seconds) / 86400 > 1 and rate(up[24h]) < 0.999
        for: 1h
        labels:
          severity: critical
          service: sla-monitoring
        annotations:
          summary: "Enterprise SLA uptime breach"
          description: "24-hour uptime {{ $value | humanizePercentage }} below 99.9% SLA"
          action: "Implement immediate corrective measures for SLA compliance"
          sla_impact: "Enterprise contract SLA violation"

      - alert: PerformanceSLABreach
        expr: histogram_quantile(0.95, rate(trinity_request_duration_seconds_bucket[1h])) > 10
        for: 30m
        labels:
          severity: warning
          service: sla-monitoring
        annotations:
          summary: "Performance SLA at risk"
          description: "Sustained high response times may breach performance SLA"
          action: "Optimize Ultimate AI Trinity coordination and resource allocation"