# Polka-Trinity Ultimate AI Trinity - Prometheus Configuration
# Enterprise monitoring for trillion-parameter governance intelligence
#
# Monitoring Strategy:
# - Ultimate AI Trinity model performance tracking
# - Multi-Xnode infrastructure health validation
# - Enterprise SLA compliance verification
# - Cost efficiency metrics ($0 AI operational costs)

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'polka-trinity-ultimate'
    environment: 'production'
    infrastructure: 'multi-xnode-sovereign'

# Enterprise alerting rules
rule_files:
  - "alerts.yml"

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations for Ultimate AI Trinity monitoring
scrape_configs:
  # Polka-Trinity Ultimate AI API
  - job_name: 'polka-trinity-api'
    static_configs:
      - targets: ['polka-trinity:8099']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Ultimate AI Trinity Model Performance
  - job_name: 'ultimate-ai-trinity'
    static_configs:
      - targets: ['polka-trinity:8099']
    metrics_path: '/trinity/metrics'
    scrape_interval: 30s
    scrape_timeout: 15s
    honor_labels: true
    params:
      models: ['deepseek-r1', 'llama4-maverick', 'qwen3']

  # Multi-Xnode Infrastructure Health
  - job_name: 'multi-xnode-infrastructure'
    static_configs:
      - targets: 
        - '23.92.65.57:9100'  # Privacy Xnode
        - '23.92.65.18:9100'  # Performance Xnode
    metrics_path: '/metrics'
    scrape_interval: 30s
    honor_labels: true

  # PostgreSQL Database Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis Cache Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Container Resource Monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s

# Enterprise retention and storage
storage:
  retention: "30d"
  retention_size: "10GB"

# Remote write for enterprise backup (optional)
# remote_write:
#   - url: https://enterprise-metrics.nuru.network/api/v1/write
#     headers:
#       Authorization: "Bearer ${REMOTE_WRITE_TOKEN}"

# Enterprise query logging
query_log_file: "/prometheus/query.log"