name: Deploy Treasury Command Center Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'website/**'
      - '.github/workflows/deploy-docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'website/**'

jobs:
  deploy:
    name: Deploy to nuru.network
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: website/package-lock.json
        
    - name: Install dependencies
      run: |
        cd website
        npm ci
        
    - name: Build website
      run: |
        cd website
        npm run build
        
    - name: Deploy to nuru.network
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploying to nuru.network/treasury-monitoring/docs/"
        echo "Build directory: website/build"
        echo "Target URL: https://nuru.network/treasury-monitoring/docs/"
        
        # Add your deployment commands here
        # Example for rsync deployment:
        # rsync -avz --delete website/build/ user@nuru.network:/var/www/nuru.network/treasury-monitoring/docs/
        
        # Example for FTP deployment:
        # lftp -c "set ftp:ssl-allow no; open -u $FTP_USER,$FTP_PASS $FTP_HOST; mirror -R website/build/ /public_html/treasury-monitoring/docs/ --delete"
        
        # Example for AWS S3 deployment:
        # aws s3 sync website/build/ s3://nuru-network-bucket/treasury-monitoring/docs/ --delete
        
        # For now, we'll just show the build was successful
        echo "✅ Build completed successfully"
        echo "📁 Build files ready for deployment"
        ls -la website/build/
        
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 Documentation build completed successfully!\n\nPreview will be available at: https://nuru.network/treasury-monitoring/docs/\n\nBuild artifacts are ready for deployment.'
          })

# Environment variables needed (add these to GitHub repository secrets):
# - FTP_USER (if using FTP deployment)
# - FTP_PASS (if using FTP deployment) 
# - FTP_HOST (if using FTP deployment)
# - AWS_ACCESS_KEY_ID (if using AWS S3)
# - AWS_SECRET_ACCESS_KEY (if using AWS S3)
# - SSH_KEY (if using SSH/rsync deployment)
# - DEPLOY_HOST (deployment target host)
# - DEPLOY_USER (deployment user)
# - DEPLOY_PATH (deployment path on server)